<a href="https://colab.research.google.com/github/it5joys135/ML-Projects/blob/main/Model_Deployment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

In [ ]:
data = files.upload()

Saving Advertising.csv to Advertising.csv


In [ ]:
df = pd.read_csv('Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [ ]:
df.describe().T

count      mean        std  min     25%     50%      75%    max
TV         200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
radio      200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
newspaper  200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0
sales      200.0   14.0225   5.217457  1.6  10.375   12.90   17.400   27.0

In [ ]:
X = df.drop('sales', axis=1)
y = df['sales']

In [ ]:
# TRAIN (70%) / VALIDATION (15%) / TEST OR HOLD OUT SET (15%)
# 1st SPLIT ---> 70/30
# 2nd SPLIT ----> 50/50

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [ ]:
X_val, X_holdout_test, y_val, y_holdout_test = train_test_split(X_test, y_test, test_size=0.5, random_state=101)

In [ ]:
len(X)

200

In [ ]:
len(X_train)

140

In [ ]:
len(X_val)

30

In [ ]:
len(X_holdout_test)

30

# **Model Training**

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model = RandomForestRegressor(n_estimators=3, random_state=101)
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=3, random_state=101)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
pred = model.predict(X_val)
pred

array([14.43333333,  6.46666667,  5.1       , 15.16666667, 11.4       ,
        9.96666667, 11.63333333, 12.1       , 19.        ,  7.03333333,
       12.43333333, 21.9       , 13.13333333,  7.2       , 11.7       ,
        7.56666667, 14.26666667, 12.6       , 11.16666667,  7.9       ,
       12.93333333, 21.2       , 19.66666667, 15.76666667, 15.9       ,
       25.06666667, 20.4       ,  9.83333333, 14.56666667, 19.66666667])

In [ ]:
mean_absolute_error(y_val, pred)

0.853333333333333

In [ ]:
np.sqrt(mean_squared_error(y_val, pred))

1.1031268688998959

In [ ]:
df.describe()['sales']

count    200.000000
mean      14.022500
std        5.217457
min        1.600000
25%       10.375000
50%       12.900000
75%       17.400000
max       27.000000
Name: sales, dtype: float64

In [ ]:
model = RandomForestRegressor(n_estimators=30, random_state=101)
model.fit(X_train, y_train)
pred = model.predict(X_val)
pred

array([14.40333333,  5.47333333,  4.14      , 15.72666667, 11.66666667,
        9.93      , 10.83333333, 11.48      , 18.02      ,  7.60333333,
       10.9       , 21.44333333, 14.08333333,  7.53333333, 11.81333333,
        6.83      , 13.51      , 13.62      , 11.01333333,  7.99666667,
       12.53333333, 21.63      , 19.49      , 15.73      , 16.05666667,
       24.21666667, 20.17666667,  9.50666667, 14.50333333, 19.36333333])

In [ ]:
mean_absolute_error(y_val, pred)

0.6575555555555552

In [ ]:
np.sqrt(mean_squared_error(y_val, pred))

0.8542009478215644

# **Final Performance Metrics (Holdout set)**

In [ ]:
holdout_pred = model.predict(X_holdout_test)

In [ ]:
mean_absolute_error(y_holdout_test, holdout_pred)

0.5937777777777775

In [ ]:
np.sqrt(mean_squared_error(y_holdout_test, holdout_pred))

0.745323693040418

In [ ]:
final_model = RandomForestRegressor(n_estimators=30, random_state=101)
final_model.fit(X, y)

RandomForestRegressor(n_estimators=30, random_state=101)

In [ ]:
import joblib

In [ ]:
joblib.dump(final_model, 'final_model.pkl')

['final_model.pkl']

In [ ]:
list(X.columns)

['TV', 'radio', 'newspaper']

In [ ]:
joblib.dump(list(X.columns), 'col_names.pkl')

['col_names.pkl']

# **Loading Model**

In [ ]:
new_columns = joblib.load('col_names.pkl')

In [ ]:
new_columns

['TV', 'radio', 'newspaper']

In [ ]:
loaded_model = joblib.load('final_model.pkl')

In [ ]:
loaded_model.predict([[230, 37, 69]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([21.83666667])